// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Steego.Web")>]
[<assembly: AssemblyProductAttribute("Steego.NET")>]
[<assembly: AssemblyDescriptionAttribute("A Collection of .NET Utilities")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Steego.Web"
    let [<Literal>] AssemblyProduct = "Steego.NET"
    let [<Literal>] AssemblyDescription = "A Collection of .NET Utilities"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
